jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pre checkout"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: echo "post checkout"
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - name: build
        run: |
          go build -v ./...
      - name: test
        run: |
          go test -v ./...
name: main
"on":
  pull_request:
    branches:
      - $default-branch
  push:
    branches:
      - $default-branch
