jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pre checkout"
      - uses: actions/checkout@v3
        with:
          path: myrepo
      - run: echo "post checkout"
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: build
        run: |
          go build -v ./...
      - name: test
        run: |
          go test -v ./...
name: main
"on":
  pull_request: {}
  push: {}
